import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./views/Sidebar";
import CustomProvider from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <CustomProvider>
          <div className="flex bg-slate-900 w-full xl:w-fit h-full mx-auto ">
            <Sidebar />
            {children}
          </div>
        </CustomProvider>
      </body>
    </html>
  );
}
